### ISSUE TITLE
Where is std::fmt?

### ISSUE THREAD

**Issue by neg-serg** [jwilm/racerd#34] opened 2016-03-03 11:55 UTC
I am currently doing my first steps in the rust.

I am using source from rust18 nightly and vim+ycm
with let g:ycm_rust_src_path = $HOME."/src/1st_level/rust_src18/rustc-nightly/src"

It works almost ok as far as I know, but with a strange issue:

When I try something like this:
```
[~] >> export RUST_SRC_PATH="/home/neg/src/1st_level/rust_src18/rustc-nightly/src"
[~] >> racer complete std::f
MATCH fmt,1,0,/home/neg/src/1st_level/rust_src18/rustc-nightly/src/libstd/../libcollections/fmt.rs,Module,/home/neg/src/1st_level/rust_src18/rustc-nightly/src/libstd/../libcollections/fmt.rs
MATCH ffi,1,0,/home/neg/src/1st_level/rust_src18/rustc-nightly/src/libstd/ffi/mod.rs,Module,/home/neg/src/1st_level/rust_src18/rustc-nightly/src/libstd/ffi/mod.rs
MATCH fs,1,0,/home/neg/src/1st_level/rust_src18/rustc-nightly/src/libstd/fs.rs,Module,/home/neg/src/1st_level/rust_src18/rustc-nightly/src/libstd/fs.rs
```

everyhing looks OK, std::fmt is here.

But when I am using vim+ycm there are only fs and ffi after "std::f<...>". Maybe you can explain why I've get this behaviour as far as you are racerd completer developer?

Not sure that it is a racerd bug, anyway.

**Comment by jwilm** [comment] 2016-03-03 15:54
Interesting! I was able to reproduce the problem. This seems to be an issue with racer on the rust nightly source files. However, it's not an issue with current stable source. Completing from the 1.6.0 source tree gives me this result.

![std_fmt_complete](https://cloud.githubusercontent.com/assets/4285147/13499906/fc8ac81e-e114-11e5-90e6-6dbcfe778113.png)

Going to mark this as a bug since there's an issue with newer nightlies.

**Comment by jwilm** [comment] 2016-03-03 15:54
Thanks for the report!

**Comment by jwilm** [comment] 2016-05-15 23:03
I think this was due to the change with source layout that required some changes in Racer. Closing until it's an issue again :).

**Closed by jwilm** 2016-05-15 23:03 UTC
Labels: bug
